"""make place postion int

Revision ID: a1601ab07798
Revises: a2dfefe4b9f1
Create Date: 2025-10-31 13:14:28.013847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1601ab07798'
down_revision = 'a2dfefe4b9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_endpoint_hash'))
        batch_op.drop_index(batch_op.f('unique_user_endpoint_hash'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preference_place', sa.Integer(), nullable=True))
        batch_op.drop_column('top_three')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_three', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('preference_place')

    op.create_table('push_subscriptions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', mysql.TEXT(), nullable=False),
    sa.Column('endpoint_hash', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('p256dh', mysql.VARCHAR(length=110), nullable=False),
    sa.Column('auth', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('push_subscriptions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_endpoint_hash'), ['user_id', 'endpoint_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_endpoint_hash'), ['endpoint_hash'], unique=False)

    # ### end Alembic commands ###
