"""add is_waitinglist

Revision ID: a2dfefe4b9f1
Revises: 
Create Date: 2025-10-13 00:26:20.551988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2dfefe4b9f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_waitinglist', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.drop_column('is_waitinglist')

    # ### end Alembic commands ###
