"""add adventure_requested_players

Revision ID: add_requested_players
Revises: a2dfefe4b9f1
Create Date: 2025-01-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'add_requested_players'
down_revision = 'a2dfefe4b9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table('adventure_requested_players'):
        op.create_table('adventure_requested_players',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('adventure_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('adventure_id', 'user_id', name='unique_adventure_requested_player')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table('adventure_requested_players'):
        op.drop_table('adventure_requested_players')
    # ### end Alembic commands ###
