name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pip install uv
      - name: Run backend tests
        run: |
          uv sync --extra test
          uv run pytest
        working-directory: backend/

      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: 'npm'
          cache-dependency-path: frontend/
      - run: npm ci
        working-directory: frontend/
      - run: npm test
        working-directory: frontend/
      - run: npm run build
        working-directory: frontend/
      - run: rsync -a --delete frontend/dist/spa/ backend/app/static/

      - name: Upload static assets
        uses: actions/upload-artifact@v4
        with:
          name: static-assets
          path: backend/app/static/

  build:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download static assets
        uses: actions/download-artifact@v4
        with:
          name: static-assets
          path: backend/app/static/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
